# fly.toml app configuration file generated for 04-fso-pokedex-cicd on 2025-02-22T13:22:26-05:00
app = '04-fso-pokedex-cicd'  # Ensure this is unique
primary_region = 'ewr'

# Build configuration (assumes a Dockerfile; adjust if using buildpacks)
[build]
  # Remove this section if you have a Dockerfile in the root directory
  # If no Dockerfile, uncomment and adjust:
  # builder = "paketobuildpacks/builder:base"
  # buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = "3000"  # Matches internal_port below

[processes]
  app = "node app.js"  # Assumes your entry point is app.js

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = "10s"    # Check every 10 seconds
  timeout = "2s"      # Fail if no response in 2 seconds
  grace_period = "5s" # Allow 5 seconds for app to start before checking
  method = "get"
  path = "/health"    # Endpoint to check
  protocol = "http"

[deploy]
  strategy = "canary"  # Canary deployment strategy

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1