# fly.toml app configuration file for 04-fso-pokedex-cicd
app = '04-fso-pokedex-cicd'  # Ensure this is unique
primary_region = 'ewr'

# Build configuration (assumes a Dockerfile; adjust if using buildpacks)
[build]
  # Remove this section if you have a Dockerfile in the root directory
  # If no Dockerfile, uncomment and adjust the following:
  # builder = "paketobuildpacks/builder:base"
  # buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = "3000"  # Matches internal_port below

[processes]
  app = "node app.js"  # Assumes your entry point is app.js

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'  # Stops machines when idle
  auto_start_machines = true   # Starts machines on demand
  min_machines_running = 0     # No machines running by default (cost-saving)
  processes = ['app']

# No [http_service.checks] section - health checks are optional
# Deployment strategy defaults to "rolling" (no "canary")
[deploy]
  # strategy = "rolling"  # Optional: this is the default, so it can be omitted

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1